### PR TITLE
add exoplayer node sample

### PR DESCRIPTION
**Pull request by green7night**

### CODE REVIEW

**Comment by erikhric** [comment]
Kudos on that!

**Comment by erikhric** [comment]
Does it support alpha channel in .webm?

**Comment by green7night** [comment]
@erikhric 
Support is not possible because the Exoplayer does not support the alpha channel.
-> https://github.com/google/ExoPlayer/issues/7789

**Comment by erikhric** [comment]
Was the original scene form video node using exoplayer too? I saw there is an option to use ChromaKeying materia to achive transparency. Can we also use matte masks? Simply synchronize 2 videos - mask and content?

**Comment by erikhric** [comment]
What about displaying transparent webview that plays transparent video. Which approach seems doable to you?

**Review by ThomasGorisse — CHANGES_REQUESTED** [review]
Thanks @green7night !
Can you please merge main and replace the `VideoMaterial` modified from your version here: https://github.com/SceneView/sceneview-android/blob/dfbe7cd355bf404b9adcd466883ef6798f8a4da5/sceneview/src/main/java/io/github/sceneview/material/VideoMaterial.kt ?

**Comment by erikhric** [comment]
Seems like `VideoTexture` supported alpha channel. It has RGB**A** pixel format: https://github.com/SceneView/sceneview-android/blob/dfbe7cd355bf404b9adcd466883ef6798f8a4da5/sceneview/src/main/java/io/github/sceneview/texture/VideoTexture.kt

**Comment by ThomasGorisse** [comment]
The texture yes but not the player.
You can try replacing the alpha channel with a RGB one and use it as chroma key.

**Review by ThomasGorisse — APPROVED** [review]

**Pull request merged**
