### PR TITLE
Fixed issue when callbacks like ARScene.onSessionConfiguration and onSessionCreated are not called because they haven't been set up yet.

### PR DESCRIPTION
**Pull request by akrupczynskirezolve**
regarding this discussion:
https://discord.com/channels/893787194295222292/895209031700979752/1168497095611793478

### CODE REVIEW

**Comment by giandifra** [comment]
I have this problem as well! The configure session is never called
```
 sceneView = ARSceneView(context, sharedLifecycle = lifecycle)
        sceneView.apply {
            planeRenderer.isEnabled = arConfig.planeRenderer.isEnabled;
            planeRenderer.isVisible = arConfig.planeRenderer.isVisible;
            configureSession { session, config ->
                Log.i(TAG, "configureSession")
                augmentedImages.forEach {
                    Log.i(TAG, "addAugmentedImage")
                    config.addAugmentedImage(session, it.name, it.bitmap)
                }

                config.lightEstimationMode = arConfig.lightEstimationMode
                config.depthMode = when (session.isDepthModeSupported(arConfig.depthMode)) {
                    true -> arConfig.depthMode
                    else -> Config.DepthMode.DISABLED
                }
                config.instantPlacementMode = arConfig.instantPlacementMode
            },
            ...
      }
```

**Comment by giandifra** [comment]
Hello, any news about this?

**Comment by giandifra** [comment]
Hello @akrupczynskirezolve, have you solved this problem?

**Comment by akrupczynskirezolve** [comment]
Hey @giandifra , sorry, I had to put this project on hold for a while. The last message I got from @ThomasGorisse was this: https://discord.com/channels/893787194295222292/895209031700979752/1173739366007451688 . I'm not sure if there was a new release since.

**Comment by giandifra** [comment]
> Hey @giandifra , sorry, I had to put this project on hold for a while. The last message I got from @ThomasGorisse was this: https://discord.com/channels/893787194295222292/895209031700979752/1173739366007451688 . I'm not sure if there was a new release since.

Thanks, there were some releases but without this fix!

**Comment by akrupczynskirezolve** [comment]
@giandifra Ok, I'll try to fix these conflicts tomorrow, then I'll ping Thomas to check if this can be merged anytime soon.

**Comment by akrupczynskirezolve** [comment]
@giandifra I've pinged you on discord

**Pull request closed without merging**
