### PR TITLE
Do not attempt to redirect to Play Store to install ARCore on unsupported devices

### PR DESCRIPTION
**Pull request by kmayoral**
**Do not attempt to redirect to Play Store to install ARCore on unsupported devices**

The current implementation does not take into account whether or not a device supports ARCore when determining if an attempt to install ARCore should be made. This results in the user being redirected to the play store listing of the AR Core library with messaging stating that the library is not available on their current device. 

This change makes is so that any attempt to install ARCore on an unsupported device will throw an `UnavailableDeviceNotCompatibleException` exception instead which will be propagated to the calling application via the `onArSessionFailed` callback. The calling application will then be able to handle the case properly and cancel the AR flow or fallback to another non-AR solution.

### CODE REVIEW

**Comment by kmayoral** [comment]
Any additional context I could have provided here @grassydragon / @ThomasGorisse or in the associated issue submission? 

I'd like to be able to update to the latest version of the library but this change has been something we've seen help our apps for the last few months so I think it (or something like it) would be beneficial. Thanks again for a great library!

**Comment by ThomasGorisse** [comment]
Reopening to merge right after main conflicts fixed @kmayoral 
Thanks

**Comment by kmayoral** [comment]
Sounds great, thanks @ThomasGorisse ! This should be ready now.

**Comment by ThomasGorisse** [comment]
Sorry for this very long time to merge. Thanks @kmayoral

**Comment by kmayoral** [comment]
No problem at all @ThomasGorisse , thank you for a great library!!

**Pull request merged**
