### PR TITLE
SceneView multiple gesture detectors

### PR DESCRIPTION
**Pull request by sarimmehdi**
I added a gesture detector but it is not working as it should. I created a sample app called sample-model-gestures to test out my gesture detector but it is very buggy. Below is the modification I made to SceneView.kt:

``` Kotlin
inner class OnGestureListener : GestureDetector.SimpleOnGestureListener() {
    override fun onSingleTapUp(motionEvent: MotionEvent): Boolean {
        val hitTestResult = surfaceGestureDetector.pickHitResult
        onTouch(hitTestResult.node, motionEvent)
        return true
    }

    override fun onDown(e: MotionEvent): Boolean {
        return true
    }

    override fun onSingleTapConfirmed(e: MotionEvent?): Boolean {
        gestureType = GestureType.SINGLE_TAP
        return super.onSingleTapConfirmed(e)
    }

    override fun onDoubleTap(e: MotionEvent?): Boolean {
        gestureType = GestureType.DOUBLE_TAP
        return super.onDoubleTap(e)
    }

    override fun onLongPress(e: MotionEvent?) {
        super.onLongPress(e)
        gestureType = GestureType.LONG_PRESS
    }

    // https://gist.github.com/TheIcemanCometh/57d0f9ae7b70dcdcc4d9
    override fun onFling(
        e1: MotionEvent?,
        e2: MotionEvent?,
        velocityX: Float,
        velocityY: Float
    ): Boolean {
        if (e1 != null && e2 != null) {
            val diffY = abs(e1.y - e2.y)
            val diffX = abs(e1.x - e2.x)
            if (diffY > SWIPE_MAX_OFF_PATH) {
                if (diffX > SWIPE_MAX_OFF_PATH || abs(velocityY) < SWIPE_THRESHOLD_VELOCITY) {
                    return false
                }
                if (e1.y - e2.y > SWIPE_MIN_DISTANCE) {
                    gestureType = GestureType.FLING_UP
                }
                else if (e2.y - e1.y > SWIPE_MIN_DISTANCE) {
                    gestureType = GestureType.FLING_DOWN
                }
            }
            else {
                if (abs(velocityX) < SWIPE_THRESHOLD_VELOCITY) {
                    return false
                }
                if (e1.x - e2.x > SWIPE_MIN_DISTANCE) {
                    gestureType = GestureType.FLING_LEFT
                }
                else if (e2.x - e1.x > SWIPE_MIN_DISTANCE) {
                    gestureType = GestureType.FLING_RIGHT
                }
            }
        }
        return super.onFling(e1, e2, velocityX, velocityY)
    }
}
```

Please have a look and let me know what I could be doing wrong. Thanks!

### CODE REVIEW

**Comment by ThomasGorisse** [comment]
Great work guys.
Quick question; Why not using the Filament [GestureDetector](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/GestureDetector.kt) ?
We should definetly merge this PR with this one: https://github.com/SceneView/sceneview-android/pull/38
And include the Filament [Camera Manipulator](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java) for 3D only usage
Sample usage: https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt

**Comment by ThomasGorisse** [comment]
Could you include the filament the new Filament pick function in order to replace the way a model is selected?
I have made some test with it and it seems to sometimes return a picked entity inside the `filamentAsset?.entities` and sometimes an other to found.
sceneView.onTouchEvent = { pickHitResult, motionEvent ->
            sceneView.renderer.filamentView.pick(motionEvent.x.toInt(), motionEvent.y.toInt(), Handler()) { pickHitResult ->
                val root = modelNode.modelInstance?.filamentAsset?.root
                val entities = modelNode.modelInstance?.filamentAsset?.entities
                val root01: Int = Filament.transformManager.getInstance(modelNode.modelInstance!!.entity)

                val root02: Int = EngineInstance.getEngine().renderableManager.getInstance(root!!)
                println(root)
                println(entities)
                println(root01)
                println(root02)
                println(pickHitResult)
            }
            true
        }

**Comment by sarimmehdi** [comment]
@ThomasGorisse sure, I will try to do that this week and update my commit

**Comment by sarimmehdi** [comment]
@ThomasGorisse sure, I will try to do that this week and update my commit

**Comment by ThomasGorisse** [comment]
Hi @sarimmehdi,

@StevenMOG have worked a lot on another PR including gesture detection https://github.com/SceneView/sceneview-android/pull/38
Maybe it's a better choice to bring your work inside this one.
The Filament Pick API has been included.
There are still some fix to do.
Could you clone the other PR branch and help us there?

Thanks

**Comment by grassydragon** [comment]
Please wait until I push the changes that make the fling gestures easier to do in my understanding :sweat_smile:

**Comment by ThomasGorisse** [comment]
Don't worry, we will try to mix everything at the end.
I already have 8 instances of Android Studio opened between PRs branches on SceneView, Sceneform, Kotlin-math, Filament. Whole having to merge each others so one more is not a problem.
Just make sure to alway Fetch and Pull before Commit.

**Comment by ThomasGorisse** [comment]
Could you check that's it's well handled in here? https://github.com/SceneView/sceneview-android/blob/ac7ab54151285e09e0d3eb83e2dd3769e95bcdd7/sceneview/src/main/kotlin/io/github/sceneview/interaction/GestureDetector.kt#L78

**Comment by grassydragon** [comment]
Do you mean whether there are conflicts between the Filament and Android gesture detectors?
As I can see the Filament gesture detector implements the gesture recognition from scratch (not using the Android gesture detector).

**Comment by ThomasGorisse** [comment]
Yep, Filament one is in C++, because of multiplatforms.
First tests on the Filament detecors sometimes return a wrong delta mostly on RotationGesture.
But also, the Filament pick API, CameraManipulator and ArNodeManipulator seems to work correctly on #38
Do you think you could include this PR into the #38 ?

**Comment by grassydragon** [comment]
> Yep, Filament one is in C++, because of multiplatforms.

Are sure? The link that you've shared contains a full implementation in Kotlin.

> Do you think you could include this PR into the #38 ?

If we want to integrate it into the Filament gesture detector, we will need to implement the recognition of the missing gestures.

I'm not sure if it is correct to handle global gestures (performed on the screen and optionally having a selected node) in the class that controls a particular `Manipulator`.

**Comment by StevenMOG** [comment]
The GestureDetector itself is a stripped-down version of Android's GestureDetector. This part is pure Kotlin. The CameraManipulator on the other hand is a mostly C++. I've decoupled the GestureDetector from the (Camera) Manipulator so that gestures in the 3D SceneView manipulate the camera while the ArNodeManipulator in ArSceneView manipulates the currently selected node (like it used to be in Google's Sceneform).

**Comment by grassydragon** [comment]
So we can extend the standard Android [GestureDetector](https://developer.android.com/reference/android/view/GestureDetector) in order not to write the recognition code ourselves and add the functionality related to controlling the `Manipulator` and calling the global `OnGestureListener`, am I right?

**Comment by StevenMOG** [comment]
The [GestureDetector ](https://github.com/google/filament/blob/main/android/filament-utils-android/src/main/java/com/google/android/filament/utils/GestureDetector.kt) is taken from Filament and provides the needed events to Manipulator. All I did was to extend it in order to support twist gestures for rotating objects in AR. What kind of interactions do you need on the nodes that would be supported by Android's GestureDetector?

**Comment by grassydragon** [comment]
> What kind of interactions do you need on the nodes that would be supported by Android's GestureDetector?

Single and double taps, a long press and a fling gesture from the [SimpleOnGestureListener](https://developer.android.com/reference/android/view/GestureDetector.SimpleOnGestureListener).

**Comment by StevenMOG** [comment]
Double taps is something I could need in my own project :) @ThomasGorisse mentioned in #38 that Filament's GestureDetector also seems to have some issues. Should your Single and double taps, etc. also manipulate Nodes? I'm thinking about whether to have two GestureDetectors (One for nodes and one for View-related gestures) or just one.

**Comment by grassydragon** [comment]
> Should your Single and double taps, etc. also manipulate Nodes?

I don't have currently a use case in my mind but we can use the return value from the `OnGestureListener` to decide whether we should manipulate the node or the listener overrides the default behavior.

**Comment by grassydragon** [comment]
> I'm thinking about whether to have two GestureDetectors (One for nodes and one for View-related gestures) or just one.

In my opinion one `GestureDetector` makes it easier to understand the source code since all events are processed there. While two `GestureDetectors` allow to completely separate the node or camera control and the user defined handlers, I think it is better to have one `GestureDetector` inside the `SceneView` and use separate handlers inside the `GestureDetector` if needed.

**Comment by ThomasGorisse** [comment]
> Double taps is something I could need in my own project :) @ThomasGorisse mentioned in #38 that Filament's GestureDetector also seems to have some issues. Should your Single and double taps, etc. also manipulate Nodes? I'm thinking about whether to have two GestureDetectors (One for nodes and one for View-related gestures) or just one.

Actually the issue only appears on the Twist (Rotation) Gesture.

**Comment by StevenMOG** [comment]
> Actually the issue only appears on the Twist (Rotation) Gesture.
Ok, then it's just my addition to Filament's GestureDetector that causing problems. I'll fix it. Given this I'd propose to keep the GestureDetector in #38. It will add transformations to SceneView again. It's based on the work of the Filament team and will work with Manipulator just fine. A gesture detector for double taps etc. would be very useful but it shouldn't be mixed with the stuff in #38.

**Comment by grassydragon** [comment]
> Given this I'd propose to keep the GestureDetector in https://github.com/SceneView/sceneview-android/pull/38.

I also noticed that Android doesn't implement all the required gesture types for the node or camera control. And recognition of some gestures is implemented in separate `GestureDetector`s, for example, [ScaleGestureDetector](https://developer.android.com/reference/android/view/ScaleGestureDetector?hl=en).

**Comment by sarimmehdi** [comment]
Hello. I am coming here after a long time (was away on holidays) and just wanted to check whether anything needs to be done. I see a lot of messages but I do not know what is being worked on here at the moment @grassydragon @ThomasGorisse

**Comment by grassydragon** [comment]
Hi!
We've discussed whether we should unite two `GestureDetector`s together and decided that we won't do it at the current stage since the Android `GestureDetector` that can recognize single and double taps, long presses and fling gestures doesn't bring anything to the `GestureDetector` that is used for the camera or model control where the drag, scale and twist gestures are required.
I think we will rebase and merge this pull request after this one: https://github.com/SceneView/sceneview-android/pull/38

**Comment by ThomasGorisse** [comment]
I confirm. You can have a look at latest #38 commit to see how it will be handled

**Comment by sarimmehdi** [comment]
OK, thank you. Let me know if you need me to make any change on this PR

**Comment by ThomasGorisse** [comment]
@sarimmehdi Thanks a lot for your contributions and sorry for this PR even if it deserves as a guide to go in the right direction for #38 
Is you're interseted in doing more things in here, there are some todos listed here:
https://github.com/orgs/SceneView/projects/2/views/1
You can assign yourself to the one you want. I'll give you the conrtibutor role in order for you to push directly on this repo.

**Comment by sarimmehdi** [comment]
Hmm, so is this pr needed anymore or will it be merged after work on 38 is completed?

**Comment by ThomasGorisse** [comment]
It will be inside #38
Have a look at `SceneGestureDetector`

**Comment by ThomasGorisse** [comment]
Don't close it. You will be able to merge your Swipe detection within #38

**Comment by sarimmehdi** [comment]
Hello, it seems #38 has been merged. Do I need to make any changes here to allow this to be merged?

**Comment by grassydragon** [comment]
Hi!
We should rebase the changes onto the `main` branch (probably moving them to the most appropriate place). Additionally, we need to decide whether we should create a separate sample application in order not to overload the main sample application (it is also possible to use another model so that gestures are easier to perform).
Currently, the node picking isn't working completely right because an entity inside the model is returned and we need to fix it by finding the root entity that corresponds to the node.

**Comment by ThomasGorisse** [comment]
Should we merge it?

**Comment by grassydragon** [comment]
Yes, but it isn't ready yet.

**Comment by ThomasGorisse** [comment]
It looks like it is not merged in main.
@sarimmehdi Could you make the merge?

**Comment by sarimmehdi** [comment]
@ThomasGorisse there are conflicts when I try to merge

```
Auto-merging samples/ar-cursor-placement/src/main/kotlin/io/github/sceneview/sample/arcursorplacement/MainFragment.kt
CONFLICT (content): Merge conflict in samples/ar-cursor-placement/src/main/kotlin/io/github/sceneview/sample/arcursorplacement/MainFragment.kt
Auto-merging sceneview/src/main/kotlin/io/github/sceneview/SceneView.kt
CONFLICT (content): Merge conflict in sceneview/src/main/kotlin/io/github/sceneview/SceneView.kt
Automatic merge failed; fix conflicts and then commit the result.
```
Please advise me how to deal with these

**Comment by sarimmehdi** [comment]
@ThomasGorisse @grassydragon can you please tell me how to deal with the conflict? Thank you!

**Comment by sarimmehdi** [comment]
@ThomasGorisse @grassydragon I merged gesture-detector into main. Please check if everything is fine now.

**Comment by sarimmehdi** [comment]
How would you advise I go on about this then? I opened this PR quite a while back and it seems too many changes have taken place since I opened the PR.

**Comment by sarimmehdi** [comment]
Hmm it seems gesture detector has now been added by you. Should I close this then?

**Comment by grassydragon** [comment]
Let's just create a new pull request and transfer the missing changes from here. Don't forget to update your fork to the latest `main` branch.

**Pull request closed without merging**
