### PR TITLE
Fix crash on model destroy by lifecycle

### PR DESCRIPTION
**Pull request by aleyooop**
Fix for [#145](https://github.com/SceneView/sceneview-android/issues/145)

### CODE REVIEW

**Comment by pecapela** [comment]
Are we expecting to have this in the next release?
And if so when is the next release?

**Comment by grassydragon** [comment]
Hi!
Thank you for the pull request!

> Are we expecting to have this in the next release?

There are plans to move away from lifecycle events to manual management of Filament entities so this shouldn't be a problem in the new version.

> And if so when is the next release?

I'm sorry but I can't give an estimate since, while we are getting close to the desired vision of the framework, this work is done in free time. However, we'll be absolutely happy when the project becomes widely supported by the community and has regular releases.

**Comment by pecapela** [comment]
@grassydragon Thanks for the response.
In the mean while I found a work around.
When you start the models like ArModelNode, just put the lifecycle as null and should not crash.

**Comment by gabrielazwaat** [comment]
Hello pecapela can you please add the version should we put inside gradle implemetation to fix the issue

**Comment by AMarquis1** [comment]
Hello, same thing happens for me. I rollback to 0.8.0 until this fix is merge

**Comment by bankbiz** [comment]
> Hello, same thing happens for me. I rollback to 0.8.0 until this fix is merge

v0.8.0 also help me

**Comment by tamashalcyon** [comment]
Are there any news about this crash? It's the same issue we see in : https://github.com/SceneView/sceneview-android/issues/176

**Comment by ThomasGorisse** [comment]
Fixed in main by completely removing lifecycle

**Pull request closed without merging**
