### PR TITLE
Verify Gradle action

### PR DESCRIPTION
**Pull request by hannesa2**
It's never checked, if Gradle is compromised

### CODE REVIEW

**Comment by grassydragon** [comment]
Hi @hannesa2!
Thank you for your pull request!
Could you provide a link to read more about the Gradle wrapper validation that you've added?

**Comment by hannesa2** [comment]
here it is https://github.com/gradle/wrapper-validation-action

**Comment by grassydragon** [comment]
> Btw, are you interested in auto update of your dependencies ? https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

I'll take a look. Thank you!

**Comment by hannesa2** [comment]
Here you see a running example https://github.com/hannesa2/paho.mqtt.android/blob/master/.github/dependabot.yml

**Pull request closed without merging**
