### PR TITLE
Fixed ViewNode being not rendered

### PR DESCRIPTION
**Pull request by grassydragon**
However, the view looks overexposed. Have you adjusted anything related to the physical camera settings?

### CODE REVIEW

**Comment by RGregat** [comment]
My ViewRenderables are looking fine, but I have disabled the LightEstimation. My problem is that all ViewNodes are rendered at the Origin of the ARCore-Coordinatesystem. 

```java
// Why is the PlacementMode so important and why is the session config updated for every created ArNode?
ArNode baseArNode = new ArNode(PlacementMode.BEST_AVAILABLE);
baseArNode.setAnchor(anchor);
baseArNode.setVisible(true);
arSceneView.addChild(baseArNode);
```

**Comment by grassydragon** [comment]
> My problem is that all ViewNodes are rendered at the Origin of the ARCore-Coordinatesystem.

Yes, I think that is because they aren't hidden by default and `(0, 0, 0)` is the default position.

> Why is the PlacementMode so important and why is the session config updated for every created ArNode?

I think the idea is to make the common use case of placing a model in AR simple without the need for diving into the ARCore API.

**Comment by ThomasGorisse** [comment]
>     My problem is that all ViewNodes are rendered at the Origin of the ARCore-Coordinatesystem.
> Yes, I think that is because they aren't hidden by default and (0, 0, 0) is the default position.

I didn't thought about it but yes it could be a good idea to hide an ArNode until it obtain it first pose. Can you handle it?

>     Why is the PlacementMode so important and why is the session config updated for every created ArNode?
> I think the idea is to make the common use case of placing a model in AR simple without the need for diving into the ARCore API.

That's it. The goal was to easily allow users to add an `ArModelNode` to the `SceneView`  without having to know what a session is.
But it's also true that this generates an inconsistent behavior between the `Node` level config and the `SceneView` one.
Also feel free here to modify it since this part was made too quick without a global framework point of view.

**Comment by grassydragon** [comment]
I'll merge this pull request to benefit from the fix in the main branch.

**Pull request merged**
